### ISSUE TITLE
add google lighthouse for performance testing

### ISSUE THREAD

**Issue by kaandesu** [kaandesu/vite-vue-ultimate-starter#19]
https://www.npmjs.com/package/lighthouse

**Comment by kaandesu** [comment]
also create a workflow after adding like
```yml
name: Lighthouse Audit

on: push

jobs:
  audit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Install dependencies
      run: |
        npm install -g lighthouse
        npm install
    - name: Run Lighthouse audit
      run: |
        lighthouse https://example.com --output json --output-path ./lighthouse-report.json
    - name: Upload Lighthouse report
      uses: actions/upload-artifact@v2
      with:
        name: Lighthouse report
        path: ./lighthouse-report.json
```
